version: '3.8'

services:
  securevault:
    build: .
    container_name: securevault
    ports:
      - "8000:8000"
    volumes:
      - ./vault-data:/app/vault
      - ./backup-data:/app/backups
      - ./logs:/app/logs
    environment:
      - SECUREVAULT_HOST=0.0.0.0
      - SECUREVAULT_PORT=8000
      - SECUREVAULT_SESSION_TIMEOUT=300
      - SECUREVAULT_MAX_ATTEMPTS=5
      - SECUREVAULT_PBKDF2_ITERATIONS=100000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - securevault-network

networks:
  securevault-network:
    driver: bridge
