#!/usr/bin/env python3
"""
Show what the web interface looks like
"""

def show_web_interface():
    print("🌐 Web Interface Preview")
    print("=" * 30)
    print()
    print("When you visit http://127.0.0.1:PORT, you'll see:")
    print()
    print("┌─────────────────────────────────────────────────┐")
    print("│          🔐 Secure Credential Manager           │")
    print("│                                                 │")
    print("│  ┌─────────────────────────────────────────┐    │")
    print("│  │              Login                      │    │")
    print("│  │                                         │    │")
    print("│  │  Master Password: [******************]  │    │")
    print("│  │                                         │    │")
    print("│  │              [Login]                    │    │")
    print("│  │                                         │    │")
    print("│  │     Need to create a new vault?        │    │")
    print("│  └─────────────────────────────────────────┘    │")
    print("└─────────────────────────────────────────────────┘")
    print()
    print("After login, you'll see the main interface:")
    print()
    print("┌─────────────────────────────────────────────────┐")
    print("│    🔐 Secure Credential Manager    [Logout]     │")
    print("│                                                 │")
    print("│  ┌─────────────────────────────────────────┐    │")
    print("│  │           Add New Credential            │    │")
    print("│  │                                         │    │")
    print("│  │  Service Name: [Gmail              ]    │    │")
    print("│  │  Username:     [john@gmail.com    ]    │    │")
    print("│  │  Password:     [******************]    │    │")
    print("│  │  Notes:        [Personal email    ]    │    │")
    print("│  │  Tags:         [email, personal   ]    │    │")
    print("│  │                                         │    │")
    print("│  │            [Add Credential]             │    │")
    print("│  └─────────────────────────────────────────┘    │")
    print("│                                                 │")
    print("│  ┌─────────────────────────────────────────┐    │")
    print("│  │          Search Credentials             │    │")
    print("│  │                                         │    │")
    print("│  │  Search: [aws                     ]     │    │")
    print("│  │          [Search] [Show All]            │    │")
    print("│  └─────────────────────────────────────────┘    │")
    print("│                                                 │")
    print("│  ┌─────────────────────────────────────────┐    │")
    print("│  │           Your Credentials              │    │")
    print("│  │                                         │    │")
    print("│  │  📧 Gmail                               │    │")
    print("│  │     Username: john@gmail.com            │    │")
    print("│  │     Password: •••••••• [Show] [Copy]    │    │")
    print("│  │     Tags: email, personal               │    │")
    print("│  │     [Delete] [Share]                    │    │")
    print("│  │                                         │    │")
    print("│  │  🔧 GitHub                              │    │")
    print("│  │     Username: johndoe                   │    │")
    print("│  │     Password: •••••••• [Show] [Copy]    │    │")
    print("│  │     Tags: development, work             │    │")
    print("│  │     [Delete] [Share]                    │    │")
    print("│  └─────────────────────────────────────────┘    │")
    print("└─────────────────────────────────────────────────┘")

def show_features():
    print("\n🎯 Web Interface Features:")
    print("   ✅ Clean, modern design")
    print("   ✅ Responsive layout (works on mobile)")
    print("   ✅ Real-time search")
    print("   ✅ Password visibility toggle")
    print("   ✅ One-click copy to clipboard")
    print("   ✅ Auto-clear clipboard (30 seconds)")
    print("   ✅ QR code generation for sharing")
    print("   ✅ Session timeout protection")
    print("   ✅ Secure sharing links")
    print("   ✅ No external dependencies")

def main():
    show_web_interface()
    show_features()
    
    print("\n🚀 To start the web interface:")
    print("   1. Run: python3 run_web.py")
    print("   2. Open: http://127.0.0.1:8000")
    print("   3. Create vault or login")
    print("   4. Start managing credentials!")
    
    print("\n🔒 Security Notes:")
    print("   • All data stays on your computer")
    print("   • Strong AES-256 encryption")
    print("   • Master password never stored")
    print("   • Session auto-locks after 5 minutes")
    print("   • Failed attempts trigger lockout")

if __name__ == "__main__":
    main()
